"""
Django settings for SinDB project.

Generated by 'django-admin startproject' using Django 2.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '!gng=aco%%)i@r2y6$hmht6aw)a1&v9_$cdnjugy2txd%$gl$7'
SECRET_KEY_FOR_AES = '!gng=aco%%)i@r2y'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*", ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'account.apps.AccountConfig',
    'db_manage.apps.DbManageConfig',
    'db_query.apps.DbQueryConfig',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SinDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SinDB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'SinDB',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': '172.17.32.218',  # Or an IP Address that your DB is hosted on
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

# STATIC_ROOT = '/var/www/html'
STATOC_ROOT = STATICFILES_DIRS

#  session
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 300 * 60
SESSION_COOKIE_NAME = 'SinDB'
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都刷新一遍session 使得用户在操作状态下session永远不会过期

# 日志配置
DJANGO_LOG_LEVEL = 'INFO'
BASE_LOG_DIR = "%s/%s" % (BASE_DIR, "logs"),

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '%(message)s - %(asctime)s [%(threadName)s:%(thread)d] [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s] '
        },
        'base': {
            'format': '%(message)s - %(asctime)s  [%(name)s:%(lineno)d] [%(module)s:%(funcName)s] [%(levelname)s]'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'base',
        },
        'base': {
            # write file ,base log
            'level': DJANGO_LOG_LEVEL,
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': '%s/SinDB.log' % BASE_LOG_DIR,
            'maxBytes': 1024 * 1024 * 50,
            'backupCount': 5,
            'formatter': 'verbose',
        },

    },
    'loggers': {
        'django': {
            'handler': ['console', "console"],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'django.request': {
            'handlers': ['base', "console"],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        'django.server': {
            'handlers': ['base', "console"],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
        'SinDB': {
            'handlers': ['base', 'console'],
            'level': DJANGO_LOG_LEVEL,
            'propagate': True,
        },
    },
}

AUTH_USER_MODEL = 'account.User'

LOGIN_URL = '/login'
SSO_LOGIN_SERVER = 'http://58.83.203.234:8088/server/'
SSO_LOGOUT_URL = 'http://58.83.203.234:8088/logout/'
SSO_PUB_KEY = "mA0wVq0Hk7XU1E2bRGt9nEReYz6AAKkCH2516GhtJ27fPs6dlnVAzo53NePr5B3F"
SSO_PRI_KEY = "FW56YwbbedsSpBJrAZ78bgMqRWb4UtpuPwEEGztZsuUHJuBqXItn5UkKC3l8VS8L"

# 普通用户展示的url
NORMAL_USER_INDEX = 'sql_query'
ADMIN_USER_INDEX = ''